### ISSUE TITLE
required_temperature oscillating without actually setting it

### ISSUE THREAD

**Issue by carloalbertobono** [chomupashchuk/ariston-remotethermo-api#4]
Hi,

I have a strange issue using the library with a Velis boiler.

When I use ApiInstanceAqua.sensor_values I get the correct value:
'required_temperature': {'value': 52.0, 'units': '°C'}

But after some time I get *another* reading:
'required_temperature': {'value': 50.0, 'units': '°C'}

This is no random number, but it's a previous setting obtained running:
ApiInstanceAqua.set_http_data(required_temperature='50')
But setting the value to 52 afterwards.

If the ApiInstanceAqua is stopped and restarted, it reads 52.0
After some time, it reads 50.0 again ...

How is this possible?

Thank you and all the best
CB

**Comment by chomupashchuk** [comment]
I have a boiler, which does not support Aqua application. All related to Aqua was created by getting people lend me remote access to boiler to try things out and basically sniff requests, which I tried to replicate.
From what I remember there are 2 Vlis types: one uses number of showers (type velis to be used) and another uses actual temperature (type lydos to be used). 
The development was done for Home Assistant in mind, where only temperatures are used and thus for first Velis type I store file with "wanted" temperature, which should have controlled number of showers, but I got denied access before I could test it properly.
Also there was an intention to show new wanted value and set actual in the background (otherwise I got question raised that it did not change when request was made even though it might take some time). But it occasioannly raised an issue that in case data cannot be changed (if you check REST requests in Aqua integration each boiler has unique requests and sometimes new things pop up) new "wanted" value is displayed but due to improper configuration or new requests types the actual temperature is not changed sucessfully.

So it sounds like you use velis type, which has very unique handling, which was not tested well. So if your Velis uses number of showers then it is preferrable to change number of showers parameter `required_showers` instead of temperature, for which it was not really designed. If your Velis uses temperatures, then make sure lydos type is used.

Frankly I'm thinking of splitting API into 2 parts and stop maintaining Aqua part as I have no equipment of my own nor I get any finnancial benefit nor experience at this point.

**Comment by carloalbertobono** [comment]
Hi, thank you for your kind reply and all the information / explanation.

I understood the situation and I must say it's quite an impressive result, given the means. And it gave me the occasion to dive into something funny!  

I was not aware of the "lydos" setting. The mobile application lets me set the temperature, while the number of showers follows (not configurable). So I guess it's worth a try! 

Thank you very much again
CB

**Comment by carloalbertobono** [comment]
Setting to "lydos" definitely worked.
Now the temperature is updated permanently and the mobile app is actually updating the screen.
I'm so happy I can manage the thing now: so a big thank you!  (I know, not that useful maybe...)
All the best
CB
